// Configuração do Supabase
const SUPABASE_URL = "https://dzfamogbogonwxgdpvbl.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_50Zeo1eoWIT7SJxvfA2W7A_N4Ls46kO";
const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Função para Salvar Atendimento
async function salvarAtendimento(status) {
    const novoAtendimento = {
            agente: document.getElementById("agente")?.value.trim() || "",
                    voo: document.getElementById("voo")?.value.trim() || "",
                            passageiro: document.getElementById("cliente")?.value.trim() || "", // Ajustado para 'passageiro' conforme a coluna real do Supabase
                                    servico: document.getElementById("servico")?.value.trim() || "",
                                            origem: document.getElementById("origem")?.value.trim() || "",
                                                    destino: document.getElementById("destino")?.value.trim() || "",
                                                            status: status,
                                                                    data: new Date().toLocaleDateString("pt-BR"),
                                                                            hora: new Date().toLocaleTimeString("pt-BR", { hour: '2-digit', minute: '2-digit' })
                                                                                };

                                                                                    try {
                                                                                            const { error } = await supabaseClient
                                                                                                        .from('atendimentos')
                                                                                                                    .insert([novoAtendimento]);

                                                                                                                            if (error) {
                                                                                                                                        console.error("Erro ao salvar:", error);
                                                                                                                                                    alert("Erro ao salvar: " + error.message);
                                                                                                                                                            } else {
                                                                                                                                                                        alert("Atendimento registrado com sucesso na nuvem!");
                                                                                                                                                                                    document.getElementById("form-atendimento")?.reset();
                                                                                                                                                                                                carregarAtendimentosDoSupabase();
                                                                                                                                                                                                        }
                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                    console.error("Erro inesperado:", err);
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                        // Função para Carregar os Atendimentos
                                                                                                                                                                                                                        async function carregarAtendimentosDoSupabase() {
                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                    const { data, error } = await supabaseClient
                                                                                                                                                                                                                                                .from('atendimentos')
                                                                                                                                                                                                                                                            .select('*')
                                                                                                                                                                                                                                                                        .order('id', { ascending: false });

                                                                                                                                                                                                                                                                                if (error) throw error;

                                                                                                                                                                                                                                                                                        const container = document.getElementById("lista-atendimentos-patio");
                                                                                                                                                                                                                                                                                                if (container && data) {
                                                                                                                                                                                                                                                                                                            if (data.length === 0) {
                                                                                                                                                                                                                                                                                                                            container.innerHTML = `<p style="color: #666; font-style: italic;">Nenhum atendimento registrado.</p>`;
                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                    container.innerHTML = data.map(a => `
                                                                                                                                                                                                                                                                                                                                                                                    <div style="border: 1px solid #ddd; padding: 10px; margin-bottom: 5px; border-radius: 4px; background: white;">
                                                                                                                                                                                                                                                                                                                                                                                                        <strong>Voo: ${a.voo}</strong> | Passageiro: ${a.passageiro || a.cliente}<br>
                                                                                                                                                                                                                                                                                                                                                                                                                            Status: <span style="font-weight:bold; color: ${a.status === 'Pendente' ? '#d97706' : '#16a34a'}">${a.status}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <br><small>Agente: ${a.agente} | ${a.data} às ${a.hora}</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error("Erro ao carregar:", err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Carregar ao abrir a página
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener("DOMContentLoaded", carregarAtendimentosDoSupabase);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    