// Configuração do Supabase
const SUPABASE_URL = "https://dzfamogbogonwxgdpvbl.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_50Zeo1eoWIT7SJxvfA2W7A_N4Ls46kO";
const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Função Mestra para Salvar (Chamada pelos botões)
async function salvarAtendimento(status) {
    const novoAtendimento = {
            agente: document.getElementById("agente")?.value.trim() || "",
                    voo: document.getElementById("voo")?.value.trim() || "",
                            cliente: document.getElementById("cliente")?.value.trim() || "",
                                    servico: document.getElementById("servico")?.value.trim() || "",
                                            origem: document.getElementById("origem")?.value.trim() || "",
                                                    destino: document.getElementById("destino")?.value.trim() || "",
                                                            status: status, // Aqui o status será "Em Curso" ou "Pendente" conforme o botão
                                                                    data: new Date().toLocaleDateString("pt-BR"),
                                                                            hora: new Date().toLocaleTimeString("pt-BR", { hour: '2-digit', minute: '2-digit' })
                                                                                };

                                                                                    try {
                                                                                            const { error } = await supabaseClient
                                                                                                        .from('atendimentos')
                                                                                                                    .insert([novoAtendimento]);

                                                                                                                            if (error) {
                                                                                                                                        console.error("Erro ao salvar:", error);
                                                                                                                                                    alert("Erro ao salvar: " + error.message);
                                                                                                                                                            } else {
                                                                                                                                                                        alert("Atendimento registrado como: " + status);
                                                                                                                                                                                    document.getElementById("form-atendimento")?.reset();
                                                                                                                                                                                                carregarAtendimentosDoSupabase();
                                                                                                                                                                                                        }
                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                    console.error("Erro inesperado:", err);
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                        // Função para Carregar (Atualizada para funcionar com as 9 colunas)
                                                                                                                                                                                                                        async function carregarAtendimentosDoSupabase() {
                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                    const { data, error } = await supabaseClient
                                                                                                                                                                                                                                                .from('atendimentos')
                                                                                                                                                                                                                                                            .select('*')
                                                                                                                                                                                                                                                                        .order('id', { ascending: false });

                                                                                                                                                                                                                                                                                if (error) throw error;

                                                                                                                                                                                                                                                                                        // Atualiza a lista na tela se o elemento existir
                                                                                                                                                                                                                                                                                                const container = document.getElementById("lista-atendimentos-patio");
                                                                                                                                                                                                                                                                                                        if (container && data) {
                                                                                                                                                                                                                                                                                                                    container.innerHTML = data.map(a => `
                                                                                                                                                                                                                                                                                                                                    <div style="border: 1px solid #ddd; padding: 10px; margin-bottom: 5px; border-radius: 4px;">
                                                                                                                                                                                                                                                                                                                                                        <strong>Voo: ${a.voo}</strong> | Cliente: ${a.cliente}<br>
                                                                                                                                                                                                                                                                                                                                                                            Status: <span style="font-weight:bold; color: ${a.status === 'Pendente' ? 'orange' : 'green'}">${a.status}</span>
                                                                                                                                                                                                                                                                                                                                                                                                <br><small>Agente: ${a.agente} | ${a.hora}</small>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            `).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error("Erro ao carregar:", err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Carregar ao abrir a página
                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener("DOMContentLoaded", carregarAtendimentosDoSupabase);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    